"""Reporter for posting updates to JIRA."""

from pathlib import Path
from typing import Any, Dict, List, Optional, Union

from src.config import settings
from src.jira.client import JiraClient, create_jira_client
from src.logger import logger
from src.state.models import JiraAgentState, TaskStatus


class JiraReporter:
    """Posts updates and reports to JIRA issues."""

    def __init__(
        self,
        client: Optional[Union[JiraClient, "SimulatedJiraClient"]] = None,
        simulated: bool = False,
    ):
        if client:
            self.client = client
        else:
            use_simulated = (
                simulated
                or not settings.is_configured()
                or settings.jira_host
                in ["", "a", "https://yourcompany.atlassian.net"]
            )
            if use_simulated:
                logger.info("Using simulated JIRA client")
            self.client = create_jira_client(simulated=use_simulated)

    def post_initial_acknowledgment(self, state: JiraAgentState) -> Optional[str]:
        """Post initial acknowledgment that the agent received the issue."""
        workflow_type = state.metadata.get("workflow_type", "unknown")
        workflow_label = workflow_type.replace("_", " ").title()

        body = f"""h3. AI Agent — Work Started

This issue has been accepted and will be processed automatically.

*Workflow:* {workflow_label}
*Status:* Analyzing requirements

Progress updates will be posted on this issue as work proceeds.
"""
        try:
            result = self.client.add_comment(state.issue_key, body)
            return result.get("id") if result else None
        except Exception as e:
            logger.error(f"Error posting acknowledgment: {e}")
            return None

    def post_plan_summary(self, state: JiraAgentState, plan_content: str) -> Optional[str]:
        """Post plan summary to JIRA."""
        lines = plan_content.strip().split("\n")
        summary_lines = [line for line in lines[:20] if line.strip()]
        summary = "\n".join(summary_lines[:10])

        body = f"""h3. AI Agent — Plan Ready

A work plan has been generated for this issue.

*Summary:*
{{code:markdown}}
{summary}
{{code}}

*Plan file:* {state.plan_path or "N/A"}

*Next steps:*
* Review the plan
* Reply with {{noformat}}/start-work{{noformat}} to begin execution
* Or reply with requested changes

----
_Plan generated by the planning agent._
"""

        result = self.client.add_comment(state.issue_key, body)

        # Merge label so existing labels (e.g. ai-assist) are preserved on Server/DC
        try:
            if hasattr(self.client, "add_labels"):
                self.client.add_labels(state.issue_key, ["ai-plan-ready"])
            else:
                self.client.update_issue(state.issue_key, labels=["ai-plan-ready"])
        except Exception as e:
            logger.warning(f"Could not add plan-ready label on {state.issue_key}: {e}")

        return result.get("id") if result else None

    def post_progress_update(
        self,
        state: JiraAgentState,
        message: str,
        progress_percentage: Optional[int] = None,
    ) -> Optional[str]:
        """Post progress update."""
        if state is None:
            logger.error("Cannot post progress: state is None")
            return None

        progress_line = ""
        if progress_percentage is not None:
            pct = max(0, min(100, int(progress_percentage)))
            progress_line = f"\n*Progress:* {pct}%\n"

        body = f"""h3. AI Agent — Progress Update

{message}{progress_line}
*Status:* {state.status.value}
"""

        result = self.client.add_comment(state.issue_key, body)
        return result.get("id") if result else None

    def post_completion(
        self,
        state: Optional[JiraAgentState],
        summary: str,
        changes_made: Optional[List[str]] = None,
    ) -> Optional[str]:
        """Post completion message (no cost or token metrics)."""
        if state is None:
            logger.error("Cannot post completion: state is None")
            return None

        changes_section = ""
        if changes_made:
            changes_list = "\n".join(f"* {c}" for c in changes_made)
            changes_section = f"""
*Changes made:*
{changes_list}
"""

        session_id = (
            getattr(state, "current_opencode_session_id", None)
            or getattr(state, "current_session_id", None)
            or "N/A"
        )
        completed_time = (
            state.completed_at.strftime("%Y-%m-%d %H:%M:%S")
            if state.completed_at
            else "N/A"
        )

        duration_line = ""
        if state.execution_duration_seconds is not None:
            duration_line = (
                f"*Duration:* {state.execution_duration_seconds:.1f} seconds\n"
            )

        body = f"""h3. AI Agent — Work Completed

{summary}{changes_section}
{duration_line}*Session:* {session_id}
*Completed at:* {completed_time}

----
_Completed by the AI agent. Please review and verify before merging or closing._
"""

        try:
            result = self.client.add_comment(state.issue_key, body)
            return result.get("id") if result else None
        except Exception as e:
            logger.error(f"Error posting completion for {state.issue_key}: {e}")
            return None

    def post_error(
        self,
        state: Optional[JiraAgentState],
        error_message: str,
        suggestion: Optional[str] = None,
    ) -> Optional[str]:
        """Post error message."""
        if state is None:
            logger.error("Cannot post error: state is None")
            return None

        suggestion_section = (
            f"\n*Suggestion:* {suggestion}\n" if suggestion else ""
        )

        timeout_section = ""
        if getattr(state, "timed_out", False):
            limit = state.timeout_seconds or "unknown"
            timeout_section = f"\n*Timed out:* yes (limit {limit}s)\n"

        retry_section = ""
        if state.max_retries and state.retry_count >= state.max_retries:
            retry_section = (
                f"\n*Retries exhausted:* {state.retry_count}/{state.max_retries}\n"
            )

        session_id = state.current_opencode_session_id or "N/A"

        body = f"""h3. AI Agent — Error

An error occurred while processing this issue:

{{code}}
{error_message}
{{code}}
{suggestion_section}{timeout_section}{retry_section}
*Status:* {state.status.value}
*Retry count:* {state.retry_count}
*Session:* {session_id}

Please review the details above and advise how to proceed (for example, move the issue back to To Do to retry).
"""

        try:
            result = self.client.add_comment(state.issue_key, body)
            return result.get("id") if result else None
        except Exception as e:
            logger.error(f"Error posting error for {state.issue_key}: {e}")
            return None

    def post_comment_response(
        self,
        issue_key: str,
        response: str,
        in_reply_to: Optional[str] = None,
    ) -> Optional[str]:
        """Post response to a comment."""
        body = f"""h3. AI Agent — Response

{response}
"""

        result = self.client.add_comment(issue_key, body)
        return result.get("id") if result else None

    def post_code_review(
        self,
        state: JiraAgentState,
        review_result: str,
        review_model: str,
    ) -> Optional[str]:
        """Post code review results to JIRA."""
        truncated_review = review_result[:3000]
        if len(review_result) > 3000:
            truncated_review += "\n\n... (review truncated)"

        body = f"""h3. AI Agent — Automated Code Review

*Review model:* {review_model}

{truncated_review}

----
_Automated code review using {review_model}. Please verify findings before merging._
"""

        result = self.client.add_comment(state.issue_key, body)

        try:
            if hasattr(self.client, "add_labels"):
                self.client.add_labels(state.issue_key, ["ai-reviewed"])
            else:
                self.client.update_issue(state.issue_key, labels=["ai-reviewed"])
        except Exception:
            pass

        return result.get("id") if result else None

    def post_oracle_response(
        self,
        issue_key: str,
        question: str,
        answer: str,
    ) -> Optional[str]:
        """Post architecture consultation response."""
        body = f"""h3. AI Agent — Architecture Consultation

*Question:* {question}

*Answer:*
{answer}

----
_Consultation provided by the Oracle agent._
"""

        result = self.client.add_comment(issue_key, body)
        return result.get("id") if result else None

    def update_issue_status(
        self,
        issue_key: str,
        status: str,
    ) -> bool:
        """Update issue status/transition."""
        return self.client.transition_issue(issue_key, status)

    def attach_file(
        self,
        issue_key: str,
        file_path: str,
        filename: Optional[str] = None,
    ) -> bool:
        """Attach a file to the issue."""
        result = self.client.add_attachment(issue_key, file_path, filename)
        return result is not None
