"""Reporter for posting updates to JIRA."""

from pathlib import Path
from typing import Any, Dict, List, Optional, Union

from src.config import settings
from src.jira.client import JiraClient, create_jira_client
from src.logger import logger
from src.state.models import JiraAgentState, TaskStatus


class JiraReporter:
    """Posts updates and reports to JIRA issues."""
    
    def __init__(self, client: Optional[Union[JiraClient, "SimulatedJiraClient"]] = None, simulated: bool = False):
        if client:
            self.client = client
        else:
            # Auto-detect: use simulated if JIRA not properly configured
            use_simulated = simulated or not settings.is_configured() or settings.jira_host in ['', 'a', 'https://yourcompany.atlassian.net']
            if use_simulated:
                logger.info("Using simulated JIRA client")
            self.client = create_jira_client(simulated=use_simulated)
    
    def post_initial_acknowledgment(self, state: JiraAgentState) -> Optional[str]:
        """Post initial acknowledgment that bot received the issue."""
        workflow_type = state.metadata.get("workflow_type", "unknown")
        
        body = f"""🤖 **AI Agent Activated**

I've received this issue and will start working on it.

**Workflow**: {workflow_type.replace('_', ' ').title()}
**Status**: Analyzing requirements...

I'll post updates as I make progress.
"""
        try:
            result = self.client.add_comment(state.issue_key, body)
            return result.get("id") if result else None
        except Exception as e:
            logger.error(f"Error posting acknowledgment: {e}")
            return None
    
    def post_plan_summary(self, state: JiraAgentState, plan_content: str) -> Optional[str]:
        """Post plan summary to JIRA."""
        # Extract summary from plan (first few lines)
        lines = plan_content.strip().split("\n")
        summary_lines = []
        for line in lines[:20]:  # First 20 lines
            if line.strip():
                summary_lines.append(line)
        
        summary = "\n".join(summary_lines[:10])  # Limit to 10 lines for comment
        
        body = f"""🤖 **Plan Generated**

I've analyzed this issue and created a work plan.

**Summary**:
```markdown
{summary}
```

The full plan is available at: `{state.plan_path}`

**Next Steps**:
- Review the plan
- Reply with `/start-work` to begin execution
- Or reply with changes/modifications

---
*Plan generated by Prometheus agent*
"""
        
        result = self.client.add_comment(state.issue_key, body)
        
        # Also add label indicating plan is ready
        self.client.update_issue(
            state.issue_key,
            labels=["ai-plan-ready"],
        )
        
        return result.get("id") if result else None
    
    def post_progress_update(
        self,
        state: JiraAgentState,
        message: str,
        progress_percentage: Optional[int] = None,
    ) -> Optional[str]:
        """Post progress update."""
        progress_bar = ""
        if progress_percentage is not None:
            filled = int(progress_percentage / 10)
            empty = 10 - filled
            progress_bar = f"\n**Progress**: [{'█' * filled}{'░' * empty}] {progress_percentage}%\n"
        
        body = f"""🤖 **Progress Update**

{message}{progress_bar}

**Status**: {state.status.value}
"""
        
        result = self.client.add_comment(state.issue_key, body)
        return result.get("id") if result else None
    
    def post_completion(
        self,
        state: Optional[JiraAgentState],
        summary: str,
        changes_made: Optional[List[str]] = None,
    ) -> Optional[str]:
        """Post completion message."""
        if state is None:
            logger.error("Cannot post completion: state is None")
            return None
            
        changes_section = ""
        if changes_made:
            changes_list = "\n".join(f"- {c}" for c in changes_made)
            changes_section = f"""\n**Changes Made**:
{changes_list}
"""
        
        session_id = (
            getattr(state, "current_opencode_session_id", None)
            or getattr(state, "current_session_id", None)
            or "N/A"
        )
        completed_time = state.completed_at.strftime("%Y-%m-%d %H:%M:%S") if state.completed_at else "N/A"
        
        # Cost info
        cost_section = ""
        if state.estimated_cost > 0:
            duration = state.execution_duration_seconds or 0.0
            cost_section = f"""\n💰 **Cost Summary**:
• Duration: {duration:.1f}s
• Input tokens: {state.token_usage_input:,}
• Output tokens: {state.token_usage_output:,}
• Total tokens: {state.token_usage_input + state.token_usage_output:,}
• Est. cost: ${state.estimated_cost:.4f}
"""
        
        body = f"""✅ **Task Completed**

{summary}{changes_section}{cost_section}

**Agent Session**: `{session_id}`
**Completed At**: {completed_time}

---
*Work completed by AI agent. Please review and verify.*
"""
        
        try:
            result = self.client.add_comment(state.issue_key, body)
            return result.get("id") if result else None
        except Exception as e:
            logger.error(f"Error posting completion for {state.issue_key}: {e}")
            return None
    
    def post_error(
        self,
        state: Optional[JiraAgentState],
        error_message: str,
        suggestion: Optional[str] = None,
    ) -> Optional[str]:
        """Post error message."""
        if state is None:
            logger.error("Cannot post error: state is None")
            return None
            
        suggestion_section = f"\n**Suggestion**: {suggestion}\n" if suggestion else ""

        timeout_section = ""
        if getattr(state, "timed_out", False):
            limit = state.timeout_seconds or "unknown"
            timeout_section = f"\n**Timed out**: yes (limit {limit}s)\n"
        retry_section = ""
        if state.max_retries and state.retry_count >= state.max_retries:
            retry_section = f"\n**Retries exhausted**: {state.retry_count}/{state.max_retries}\n"

        session_id = state.current_opencode_session_id or "N/A"
        
        body = f"""❌ **Agent Error**

An error occurred while processing this issue:

```
{error_message}
```{suggestion_section}{timeout_section}{retry_section}

**Status**: {state.status.value}
**Retry Count**: {state.retry_count}
**Agent Session**: `{session_id}`

Please review and provide guidance on how to proceed.
"""
        
        try:
            result = self.client.add_comment(state.issue_key, body)
            return result.get("id") if result else None
        except Exception as e:
            logger.error(f"Error posting error for {state.issue_key}: {e}")
            return None
    
    def post_comment_response(
        self,
        issue_key: str,
        response: str,
        in_reply_to: Optional[str] = None,
    ) -> Optional[str]:
        """Post response to a comment."""
        body = f"""🤖 **Response**

{response}
"""
        
        result = self.client.add_comment(issue_key, body)
        return result.get("id") if result else None
    
    def post_code_review(
        self,
        state: JiraAgentState,
        review_result: str,
        review_model: str,
    ) -> Optional[str]:
        """Post code review results to JIRA."""
        # Truncate very long reviews
        truncated_review = review_result[:3000]
        if len(review_result) > 3000:
            truncated_review += "\n\n... (review truncated)"

        body = f"""🔍 **Automated Code Review**

**Review Model**: `{review_model}`

{truncated_review}

---
*Code review performed automatically by AI agent using {review_model}.*
*Please verify the findings and address any concerns before merging.*
"""

        result = self.client.add_comment(state.issue_key, body)

        # Add label indicating review is done
        try:
            self.client.update_issue(
                state.issue_key,
                labels=["ai-reviewed"],
            )
        except Exception:
            pass

        return result.get("id") if result else None

    def post_oracle_response(
        self,
        issue_key: str,
        question: str,
        answer: str,
    ) -> Optional[str]:
        """Post Oracle consultation response."""
        body = f"""🔮 **Architecture Consultation**

**Question**: {question}

**Answer**:
{answer}

---
*Consultation by Oracle agent*
"""
        
        result = self.client.add_comment(issue_key, body)
        return result.get("id") if result else None
    
    def update_issue_status(
        self,
        issue_key: str,
        status: str,
    ) -> bool:
        """Update issue status/transition."""
        return self.client.transition_issue(issue_key, status)
    
    def attach_file(
        self,
        issue_key: str,
        file_path: str,
        filename: Optional[str] = None,
    ) -> bool:
        """Attach a file to the issue."""
        result = self.client.add_attachment(issue_key, file_path, filename)
        return result is not None
