name: Build Docker Image

on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Repo çek
        uses: actions/checkout@v4

      - name: Docker build
        run: docker build -t virtual_dev_env .

      - name: Image export
        run: docker save virtual_dev_env > virtual_dev_env.tar

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: docker-image
          path: virtual_dev_env.tar
